### ISSUE TITLE
ScrollView inside WelcomePageLayout

### ISSUE THREAD

**Issue by hendrawd** [txusballesteros/welcome-coordinator#10]
When i use ScrollView inside WelcomePageLayout, when scroll to right from first layout, an error will occur and application will be force closed.
Here is the stack trace:

`java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.VelocityTracker.addMovement(android.view.MotionEvent)' on a null object reference
                                                                        at com.redbooth.WelcomeCoordinatorTouchController.onTouchEvent(WelcomeCoordinatorTouchController.java:98)
                                                                        at com.redbooth.WelcomeCoordinatorLayout.onTouchEvent(WelcomeCoordinatorLayout.java:244)
                                                                        at android.view.View.dispatchTouchEvent(View.java:8472)
                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2400)
                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2093)
                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
                                                                        at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2625)
                                                                        at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1770)
                                                                        at android.app.Activity.dispatchTouchEvent(Activity.java:2742)
                                                                        at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
                                                                        at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2586)
                                                                        at android.view.View.dispatchPointerEvent(View.java:8667)
                                                                        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4129)
                                                                        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3995)
                                                                        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3550)
                                                                        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3603)
                                                                        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3569)
                                                                        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3686)
                                                                        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3577)
                                                                        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3743)
                                                                        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3550)
                                                                        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3603)
                                                                        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3569)
                                                                        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3577)
                                                                        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3550)
                                                                        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5813)
                                                                        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5787)
                                                                        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5758)
                                                                        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5903)
                                                                        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
                                                                        at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
                                                                        at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
                                                                        at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:5874)
                                                                        at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:5926)
                                                                        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
                                                                        at android.view.Choreographer.doCallbacks(Choreographer.java:580)
                                                                        at android.view.Choreographer.doFrame(Choreographer.java:548)
                                                                        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
                                                                        at android.os.Handler.handleCallback(Handler.java:739)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                        at android.os.Looper.loop(Looper.java:135)`

**Comment by txusballesteros** [comment]
Hi @hendrawd ,

Right now the component does't support that feature. I'm sorry.
