### ISSUE TITLE
NullPointerException when trying to scroll

### ISSUE THREAD

**Issue by JStav** [txusballesteros/welcome-coordinator#15]
<pre>java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.VelocityTracker.addMovement(android.view.MotionEvent)' on a null object reference
                                                                                  at com.redbooth.WelcomeCoordinatorTouchController.onTouchEvent(WelcomeCoordinatorTouchController.java:98)
                                                                                  at com.redbooth.WelcomeCoordinatorLayout.onTouchEvent(WelcomeCoordinatorLayout.java:244)
...
</pre>

It seems like there's a null check in the case MotionEvent.ACTION_DOWN of the switch but not on MotionEvent. ACTION_MOVE. ACTION_MOVE happens before velocityTracker gets obtained.

``` java
           case MotionEvent.ACTION_DOWN:
                if (velocityTracker == null) {
                    velocityTracker = VelocityTracker.obtain();
                } else {
                    velocityTracker.clear();
                }
                velocityTracker.addMovement(event);
                currentScrollX = view.getScrollX();
                iniEventX = event.getX();
                break;
            case MotionEvent.ACTION_MOVE:
                setScrollX(scrollLimited(event.getX()));
                velocityTracker.addMovement(event);
                velocityTracker.computeCurrentVelocity(CURRENT_VELOCITY);
                break;
```

Additionally, it looks like it only happens when the initial touch for scrolling is on an EditText. If it is anywhere else it works.

**Comment by GunnarAK** [comment]
Having exactly the same problem.
When in edit mode to write a string to an EditText. Scrolling to next page by touching the EditText causes this exact same error.

```
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.VelocityTracker.addMovement(android.view.MotionEvent)' on a null object reference
                                                                             at com.redbooth.WelcomeCoordinatorTouchController.onTouchEvent(WelcomeCoordinatorTouchController.java:98)
                                                                             at com.redbooth.WelcomeCoordinatorLayout.onTouchEvent(WelcomeCoordinatorLayout.java:244)
                                                                             at android.view.View.dispatchTouchEvent(View.java:10024)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2626)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2307)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
                                                                             at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:414)
                                                                             at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1808)
                                                                             at android.app.Activity.dispatchTouchEvent(Activity.java:3064)
                                                                             at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:71)
                                                                             at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:376)
                                                                             at android.view.View.dispatchPointerEvent(View.java:10244)
                                                                             at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4444)
                                                                             at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4312)
                                                                             at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3859)
                                                                             at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3912)
                                                                             at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3878)
                                                                             at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4005)
                                                                             at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3886)
                                                                             at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4062)
                                                                             at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3859)
                                                                             at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3912)
                                                                             at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3878)
                                                                             at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3886)
                                                                             at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3859)
                                                                             at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6253)
                                                                             at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6227)
                                                                             at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6188)
                                                                             at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6356)
                                                                             at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
                                                                             at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
                                                                             at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
                                                                             at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:6327)
                                                                             at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6379)
                                                                             at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
                                                                             at android.view.Choreographer.doCallbacks(Choreographer.java:686)
                                                                             at android.view.Choreographer.doFrame(Choreographer.java:615)
                                                                             at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
04-28 17:17:16.502 16487-16487/projectfolder E/AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:751)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                             at android.os.Looper.loop(Looper.java:154)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:6128)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

```

**Comment by santhoshrao519** [comment]
I'm also facing same issue, have you got any solution for this guys?
